title: jinyuzu99
author:
  name: Yuzu Jin
  email: i@9902259.xyz

description: >
  💭 think different

remote_theme: jekyll/minima

header_pages:
  - about.md

minima:
  skin: auto
  date_format: "%Y-%m-%d"
  social_links:
    - { platform: github,  user_url: "https://github.com/jinyuzu99" }
    - { platform: twitter, user_url: "https://x.com/hanabi8964_3" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
