title: jinyuzu99
author:
  name: Yuzu Jin
  email: "i@9902259.xyz"

theme: minima

minima:
  skin: auto
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/jinyuzu99" }
    - { platform: twitter, user_url: "https://x.com/hanabi8964_3" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag
